---
version: "2.0"
services:
  site:
    image: ubuntu:22.04     
    command:
      - "bash"
      - "-c"
    args:
      - 'apt-get update ; apt-get upgrade -y ; apt-get install git nginx -y ;
        git clone https://github.com/DecloudNodesLab/site;
        sed -i -e "s|root .*|root /site/;|" /etc/nginx/sites-available/default;
        service nginx start; sleep infinity'    
    expose:
      - port: 80
        to:
          - global: true		  
  explorer:
    image: ubuntu:22.04     
    command:
      - "bash"
      - "-c"
    args:
      - 'apt-get update ; apt-get upgrade -y ; apt-get install wget curl tar nginx -y ;
        wget https://github.com/DecloudNodesLab/explorer/raw/master/explorer.tar.gz; tar -xvf explorer.tar.gz && rm explorer.tar.gz;
		sed -i -e "s|root .*|root /dist;|" /etc/nginx/sites-available/default;
        service nginx start; sleep infinity'
    expose:
      - port: 80
        to:
          - global: true
profiles:
  compute:
    site:
      resources:
        cpu:
          units: 0.1
        memory:
          size: 128Mi
        storage:
          size: 256Mi
		  
    explorer:
      resources:
        cpu:
          units: 0.3
        memory:
          size: 512Mi
        storage:
          size: 350Mi
          
  placement:
    akash: 
      pricing:
        site:
          denom: uakt
          amount: 10000
        explorer:
          denom: uakt
          amount: 10000
deployment:
  site:
    akash:
      profile: site
      count: 1 
  explorer:
    akash:
      profile: explorer
      count: 1 
