---
version: "2.0"
services:
  site:
    image: dimokus88/dnlsite:0.1        
    expose:
      - port: 80
        to:
          - global: true
  explorer:
    image: dimokus88/dnlexplorer:0.1     
    env:
      - "LINK_EXPLORER=https://github.com/DecloudNodesLab/explorer/raw/master/explorer.tar.gz"
    expose:
      - port: 80
        to:
          - global: true
profiles:
  compute:
    site:
      resources:
        cpu:
          units: 0.1
        memory:
          size: 128Mi
        storage:
          size: 350Mi		  
    explorer:
      resources:
        cpu:
          units: 0.3
        memory:
          size: 512Mi
        storage:
          size: 350Mi          
  placement:
    akash: 
      pricing:
        site:
          denom: uakt
          amount: 10000
        explorer:
          denom: uakt
          amount: 10000
deployment:
  site:
    akash:
      profile: site
      count: 1 
  explorer:
    akash:
      profile: explorer
      count: 1 
