---
version: "2.0"
services:
  app:
    image: ubuntu:22.04     
    command:
      - "bash"
      - "-c"
    args:
      - 'apt-get update ; apt-get upgrade -y ; apt-get install git nginx -y ;
        git clone https://github.com/DecloudNodesLab/site;
        sed -i -e "s|root .*|root /site/;|" /etc/nginx/sites-available/default;
        service nginx start; sleep infinity'    
    expose:
      - port: 80
        as: 80
        to:
          - global: true
        accept:
          - declab.pro
profiles:
  compute:
    app:
      resources:
        cpu:
          units: 0.1
        memory:
          size: 128Mi
        storage:
          size: 350Mi
          
  placement:
    akash: 
      pricing:
        app:
          denom: uakt
          amount: 10000
deployment:
  app:
    akash:
      profile: app
      count: 1 
